name: Codacy Static Analysis

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  codacy-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Codacy Analysis CLI and upload results
        uses: codacy/codacy-analysis-cli-action@v4
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}  
          directory: .
          upload: true
          allow-network: true
          verbose: true
          max-allowed-issues: 2147483647
          skip-uncommitted-files-check: true
          skip-container-engine-check: true
          fail-if-incomplete: false
